apiVersion: v1
name: BE Helm Chart
description: Helm chart for BE Applications.

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates.
version: 1.0.0
