{{- if eq .Values.omType "cache" }}
  {{- if or (eq .Values.persistentType "None" ) (eq .Values.persistentType "sharedNothing" ) (eq .Values.persistentType "sharedAll" ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discoveryservice.fullname" . }}
spec:
  ports:
    - port: {{ .Values.discoveryservice.ports.port }}
      protocol: TCP
  selector:
    name: {{ include "bediscoverynode.fullname" . }}
  {{- end }}
{{- end }}
