apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "beinferenceagent.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "beinferenceagent.fullname" . }}
  serviceName: {{ include "beservice.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "beinferenceagent.fullname" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.inferencenode.spec.template.spec.imagePullSecrets.name }}    #if required
      containers:
      - name: {{ .Values.inferencenode.spec.template.spec.containers.name }}
        image: {{ .Values.inferencenode.spec.template.spec.containers.image }}
        env:
        - name: {{ .Values.inferencenode.spec.template.spec.containers.env.name1 }}
          value: {{ .Values.inferencenode.spec.template.spec.containers.env.value1 }}
        - name: {{ .Values.inferencenode.spec.template.spec.containers.env.name2 }}
          value: {{ .Values.inferencenode.spec.template.spec.containers.env.value2 }}
{{ include "sharedAll.first" . | indent 8 }}
{{ include "sharedNothing.first" . | indent 8 }}
{{ include "sharedNothing.inferencesecond" . }}
