kind: Service
apiVersion: v1
metadata:
  name: {{ include "jmxservice.fullname" . }}
spec:
  ports:
    - port: {{ .Values.jmxservice.spec.ports.port }}
      protocol: TCP
  selector:
    name: {{ include "bediscoverynode.fullname" . }}
  type: {{ .Values.jmxservice.spec.type }}
