{{- if and (eq .Values.persistentType "sharedAll" ) (eq .Values.omType "cache" ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commonconfigmap.fullname" . }}
  labels:
    name: {{ include "commonconfigmap.fullname" . }}
{{ include "commonconfigmap.data" . }}
{{- end }}
