{{- if or (eq .Values.isType "cache" ) (eq .Values.isType "sharedNothing" ) (eq .Values.isType "sharedAll" ) }}
  {{- if eq .Values.cloudProvider "azure" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "azurestorageclass.fullname" . }}
provisioner: {{ .Values.volumes.azure.provisioner }}
 {{- if or (eq .Values.cloudProvider "azure") }}
mountOptions:
  - dir_mode={{ .Values.volumes.azure.dir_mode }}
  - file_mode={{ .Values.volumes.azure.file_mode }}
  - uid={{ .Values.volumes.azure.uid }}
  - gid={{ .Values.volumes.azure.gid }}
parameters:
  skuName: {{ .Values.volumes.azure.skuName }}
  {{- end }}
  {{- end }}
{{- end }}
