{{- if or (eq .Values.isType "cache" ) (eq .Values.isType "sharedNothing" ) (eq .Values.isType "sharedAll" ) }}
  {{- if eq .Values.cloudProvider "aws" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eksconfigmap.fullname" . }}
{{ include "eksconfigmap.data" . }}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ include "eksdeployment.fullname" . }}
spec:
  replicas: {{ .Values.persistentvolumes.eks.deployment.replicas }}
  strategy:
    type: {{ .Values.persistentvolumes.eks.deployment.type }}
  template:
    metadata:
      labels:
        app: {{ include "eksdeployment.fullname" . }}
    spec:
      containers:
        - name: {{ .Values.persistentvolumes.eks.deployment.containername }}
          image: {{ .Values.persistentvolumes.eks.deployment.image }}
          env:
            - name: {{ .Values.persistentvolumes.eks.deployment.env1 }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.persistentvolumes.eks.deployment.configmapname }}
                  key: {{ .Values.persistentvolumes.eks.deployment.val1 }}
            - name: {{ .Values.persistentvolumes.eks.deployment.env2 }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.persistentvolumes.eks.deployment.configmapname }}
                  key: {{ .Values.persistentvolumes.eks.deployment.val2 }}
            - name: {{ .Values.persistentvolumes.eks.deployment.env3 }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.persistentvolumes.eks.deployment.configmapname }}
                  key: {{ .Values.persistentvolumes.eks.deployment.val3 }}
          volumeMounts:
            - name: {{ .Values.persistentvolumes.eks.deployment.volumename }}
              mountPath: {{ .Values.persistentvolumes.eks.deployment.mountPath }}
      volumes:
        - name: {{ .Values.persistentvolumes.eks.deployment.volumename }}
          nfs:
            server: {{ .Values.persistentvolumes.eks.deployment.nfsserver }}
            path: {{ .Values.persistentvolumes.eks.deployment.nfspath }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ include "eksstorageclass.fullname" . }}
provisioner: {{ .Values.persistentvolumes.eks.storageclass.provisioner }}
 {{- end }}
{{- end }}
