{{- if and (eq .Values.persistentType "sharedAll" ) (eq .Values.omType "cache" ) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "mysql.fullname" . }}
  serviceName: {{ include "mysqlservice.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "mysql.fullname" . }}
    spec:
      containers:
      - name: {{ .Values.mysql.containers.name }}
        image: {{ .Values.mysql.containers.image }}
        args: [ "--lower_case_table_names=1","--sql_mode=IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
        env:
        - name: {{ .Values.mysql.containers.env.mysqlusername }}
          value: {{ .Values.mysql.containers.env.mysqluserval }}
        - name: {{ .Values.mysql.containers.env.mysqlpwdname }}
          value: {{ .Values.mysql.containers.env.mysqlpwdval }}
        - name: {{ .Values.mysql.containers.env.mysqlrootpwdname }}
          value: {{ .Values.mysql.containers.env.mysqlrootpwdval }}
        - name: {{ .Values.mysql.containers.env.mysqldbname }}
          value: {{ .Values.mysql.containers.env.mysqldbval }}
        ports:
        - containerPort: {{ .Values.mysql.containers.ports.containerPort }}
{{ include "sharedAll.volumeMount" . | indent 8 }}
{{ include "sharedAll.volumeClaim" . }}
{{- end }}
